---
- name: Copy docker configuration
  ansible.builtin.copy:
    src: docker
    dest: /etc/
    mode: '0644'

- name: Copy docker systemd file
  ansible.builtin.copy:
    src: home_assistant.service
    dest: /usr/local/lib/systemd/system/
    mode: '0644'

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/home.conf
    mode: '0644'

- name: Create configuration directory
  ansible.builtin.file:
    path: /var/lib/home_assistant/
    state: directory
    mode: '0755'

- name: Restore copy
  ansible.builtin.unarchive:
    src: '{{ host.home_assistant.backup }}'
    dest: /var/lib/
    remote_src: true

- name: Copy bin
  ansible.builtin.copy:
    src: bin/
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Create hass postgresql database
  ansible.builtin.command: createdb hass
  changed_when: false
  become: true
  become_user: postgres

- name: Start systemd service
  ansible.builtin.systemd:
    state: started
    name: home_assistant
    enabled: true
