require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "beancount",
    "c",
    "css",
    "csv",
    "diff",
    "dockerfile",
    "gitignore",
    "graphql",
    "query",
    "haskell",
    "html",
    "javascript",
    "json",
    "lua",
    "markdown",
    "markdown_inline",
    "nginx",
    "python",
    "ruby",
    "scss",
    "sql",
    "ssh_config",
    "terraform",
    "tmux",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
  },

  highlight = {
    additional_vim_regex_highlighting = false,
    enable = true,
  },
})
